context("detect_column")

test_that("check if required columns exist", {
  expect_error(validate_column_names(data=data.frame(STUDYID="TEST",
                                                     DOMAIN="TEST",
                                                     USUBJID="TEST",
                                                     SUBJID="TEST",
                                                     RFSTDTC="2012-09-27",
                                                     RFENDTC="2012-09-27",
                                                     RFXSTDTC="2012-09-27",
                                                     RFXENDTC="2012-09-27",
                                                     RFICDTC="2012-09-27",
                                                     RFPENDTC="2012-09-27",
                                                     DTHDTC="2012-09-27",
                                                     DTHFL="N",
                                                     SITEID="TEST",
                                                     INVID="TEST",
                                                     INVNAM="TEST",
                                                     BRTHDTC="2012-09-27",
                                                     AGE=1,
                                                     AGEU="DAYS",
                                                     SEX="U",
                                                     RACE="NOT REPORTED",
                                                     ETHNIC="UNKNOWN",
                                                     ARMCD="TEST",
                                                     ARM="TEST",
                                                     ACTARMCD="TEST",
                                                     ACTARM="TEST",
                                                     ARMNRS="TEST",
                                                     ACTARMUD="TEST",
                                                     # COUNTRY="AFG",
                                                     DMDTC="2012-09-27",
                                                     DMDY=1),"SDTMIG3.3","DM"),
               "The following required columns are missing: COUNTRY",
  info="Required column, COUNTRY, is missing, check error message")
  expect_silent(validate_column_names(data=data.frame(STUDYID="TEST",
                                                      DOMAIN="TEST",
                                                      USUBJID="TEST",
                                                      SUBJID="TEST",
                                                      RFSTDTC="2012-09-27",
                                                      RFENDTC="2012-09-27",
                                                      RFXSTDTC="2012-09-27",
                                                      RFXENDTC="2012-09-27",
                                                      RFICDTC="2012-09-27",
                                                      RFPENDTC="2012-09-27",
                                                      DTHDTC="2012-09-27",
                                                      DTHFL="N",
                                                      SITEID="TEST",
                                                      INVID="TEST",
                                                      INVNAM="TEST",
                                                      BRTHDTC="2012-09-27",
                                                      AGE=1,
                                                      AGEU="DAYS",
                                                      SEX="U",
                                                      RACE="NOT REPORTED",
                                                      ETHNIC="UNKNOWN",
                                                      ARMCD="TEST",
                                                      ARM="TEST",
                                                      ACTARMCD="TEST",
                                                      ACTARM="TEST",
                                                      ARMNRS="TEST",
                                                      ACTARMUD="TEST",
                                                      COUNTRY="AFG",
                                                      DMDTC="2012-09-27",
                                                      DMDY=1,stringsAsFactors = F),"SDTMIG3.3","DM"))
  })

test_that("check if expected columns exist", {
  expect_warning(validate_column_names(data=data.frame(STUDYID="TEST",
                                                     DOMAIN="TEST",
                                                     USUBJID="TEST",
                                                     SUBJID="TEST",
                                                     # RFSTDTC="2012-09-27",
                                                     RFENDTC="2012-09-27",
                                                     RFXSTDTC="2012-09-27",
                                                     RFXENDTC="2012-09-27",
                                                     RFICDTC="2012-09-27",
                                                     RFPENDTC="2012-09-27",
                                                     DTHDTC="2012-09-27",
                                                     DTHFL="N",
                                                     SITEID="TEST",
                                                     INVID="TEST",
                                                     INVNAM="TEST",
                                                     BRTHDTC="2012-09-27",
                                                     AGE=1,
                                                     AGEU="DAYS",
                                                     SEX="U",
                                                     RACE="NOT REPORTED",
                                                     ETHNIC="UNKNOWN",
                                                     ARMCD="TEST",
                                                     ARM="TEST",
                                                     ACTARMCD="TEST",
                                                     ACTARM="TEST",
                                                     ARMNRS="TEST",
                                                     ACTARMUD="TEST",
                                                     COUNTRY="AFG",
                                                     DMDTC="2012-09-27",
                                                     DMDY=1,stringsAsFactors = F),"SDTMIG3.3","DM"),
               "The following expected columns are missing: RFSTDTC",
               info="Expected column RFSTDTC is missing, check warning message")
  expect_silent(validate_column_names(data=data.frame(STUDYID="TEST",
                                                      DOMAIN="TEST",
                                                      USUBJID="TEST",
                                                      SUBJID="TEST",
                                                      RFSTDTC="2012-09-27",
                                                      RFENDTC="2012-09-27",
                                                      RFXSTDTC="2012-09-27",
                                                      RFXENDTC="2012-09-27",
                                                      RFICDTC="2012-09-27",
                                                      RFPENDTC="2012-09-27",
                                                      DTHDTC="2012-09-27",
                                                      DTHFL="N",
                                                      SITEID="TEST",
                                                      INVID="TEST",
                                                      INVNAM="TEST",
                                                      BRTHDTC="2012-09-27",
                                                      AGE=1,
                                                      AGEU="DAYS",
                                                      SEX="U",
                                                      RACE="NOT REPORTED",
                                                      ETHNIC="UNKNOWN",
                                                      ARMCD="TEST",
                                                      ARM="TEST",
                                                      ACTARMCD="TEST",
                                                      ACTARM="TEST",
                                                      ARMNRS="TEST",
                                                      ACTARMUD="TEST",
                                                      COUNTRY="AFG",
                                                      DMDTC="2012-09-27",
                                                      DMDY=1,stringsAsFactors = F),"SDTMIG3.3","DM"))
})


#
test_that("check if permitted columns exist", {
  expect_silent(validate_column_names(data=data.frame(STUDYID="TEST",
                                                                DOMAIN="TEST",
                                                                USUBJID="TEST",
                                                                SUBJID="TEST",
                                                                RFSTDTC="2012-09-27",
                                                                RFENDTC="2012-09-27",
                                                                RFXSTDTC="2012-09-27",
                                                                RFXENDTC="2012-09-27",
                                                                RFICDTC="2012-09-27",
                                                                RFPENDTC="2012-09-27",
                                                                DTHDTC="2012-09-27",
                                                                DTHFL="N",
                                                                SITEID="TEST",
                                                                # INVID="TEST",
                                                                INVNAM="TEST",
                                                                BRTHDTC="2012-09-27",
                                                                AGE=1,
                                                                AGEU="DAYS",
                                                                SEX="U",
                                                                RACE="NOT REPORTED",
                                                                ETHNIC="UNKNOWN",
                                                                ARMCD="TEST",
                                                                ARM="TEST",
                                                                ACTARMCD="TEST",
                                                                ACTARM="TEST",
                                                                ARMNRS="TEST",
                                                                ACTARMUD="TEST",
                                                                COUNTRY="AFG",
                                                                DMDTC="2012-09-27",
                                                                DMDY=1,stringsAsFactors = F),"SDTMIG3.3","DM"))
  expect_silent(validate_column_names(data=data.frame(STUDYID="TEST",
                                                                DOMAIN="TEST",
                                                                USUBJID="TEST",
                                                                SUBJID="TEST",
                                                                RFSTDTC="2012-09-27",
                                                                RFENDTC="2012-09-27",
                                                                RFXSTDTC="2012-09-27",
                                                                RFXENDTC="2012-09-27",
                                                                RFICDTC="2012-09-27",
                                                                RFPENDTC="2012-09-27",
                                                                DTHDTC="2012-09-27",
                                                                DTHFL="N",
                                                                SITEID="TEST",
                                                                INVID="TEST",
                                                                INVNAM="TEST",
                                                                BRTHDTC="2012-09-27",
                                                                AGE=1,
                                                                AGEU="DAYS",
                                                                SEX="U",
                                                                RACE="NOT REPORTED",
                                                                ETHNIC="UNKNOWN",
                                                                ARMCD="TEST",
                                                                ARM="TEST",
                                                                ACTARMCD="TEST",
                                                                ACTARM="TEST",
                                                                ARMNRS="TEST",
                                                                ACTARMUD="TEST",
                                                                COUNTRY="AFG",
                                                                DMDTC="2012-09-27",
                                                                DMDY=1,stringsAsFactors = F),"SDTMIG3.3","DM"))
})

test_that("check if extra columns exist", {
  expect_warning(validate_column_names(data=data.frame(STUDYID="TEST",
                                                             DOMAIN="TEST",
                                                             USUBJID="TEST",
                                                             SUBJID="TEST",
                                                             RFSTDTC="2012-09-27",
                                                             RFENDTC="2012-09-27",
                                                             RFXSTDTC="2012-09-27",
                                                             RFXENDTC="2012-09-27",
                                                             RFICDTC="2012-09-27",
                                                             RFPENDTC="2012-09-27",
                                                             DTHDTC="2012-09-27",
                                                             DTHFL="N",
                                                             SITEID="TEST",
                                                             INVID="TEST",
                                                             INVNAM="TEST",
                                                             BRTHDTC="2012-09-27",
                                                             AGE=1,
                                                             AGEU="DAYS",
                                                             SEX="U",
                                                             RACE="NOT REPORTED",
                                                             ETHNIC="UNKNOWN",
                                                             ARMCD="TEST",
                                                             ARM="TEST",
                                                             ACTARMCD="TEST",
                                                             ACTARM="TEST",
                                                             ARMNRS="TEST",
                                                             ACTARMUD="TEST",
                                                             COUNTRY="AFG",
                                                             DMDTC="2012-09-27",
                                                             DMDY=1,
                                                             EXTRA="TEST",stringsAsFactors = F),"SDTMIG3.3","DM"),
                 "The following extra columns do exist: EXTRA",
                 info="Extra column EXTRA exists, check warning message")
  expect_silent(validate_column_names(data=data.frame(STUDYID="TEST",
                                                            DOMAIN="TEST",
                                                            USUBJID="TEST",
                                                            SUBJID="TEST",
                                                            RFSTDTC="2012-09-27",
                                                            RFENDTC="2012-09-27",
                                                            RFXSTDTC="2012-09-27",
                                                            RFXENDTC="2012-09-27",
                                                            RFICDTC="2012-09-27",
                                                            RFPENDTC="2012-09-27",
                                                            DTHDTC="2012-09-27",
                                                            DTHFL="N",
                                                            SITEID="TEST",
                                                            INVID="TEST",
                                                            INVNAM="TEST",
                                                            BRTHDTC="2012-09-27",
                                                            AGE=1,
                                                            AGEU="DAYS",
                                                            SEX="U",
                                                            RACE="NOT REPORTED",
                                                            ETHNIC="UNKNOWN",
                                                            ARMCD="TEST",
                                                            ARM="TEST",
                                                            ACTARMCD="TEST",
                                                            ACTARM="TEST",
                                                            ARMNRS="TEST",
                                                            ACTARMUD="TEST",
                                                            COUNTRY="AFG",
                                                            DMDTC="2012-09-27",
                                                            DMDY=1,stringsAsFactors = F),"SDTMIG3.3","DM"))
})


test_that("check if columns have expected class (numeric or character) and convert if necessary", {
  expect_equal(
    expect_warning(validate_column_names(data=data.frame(STUDYID=1,
                                                         DOMAIN="TEST",
                                                         USUBJID="TEST",
                                                         SUBJID="TEST",
                                                         RFSTDTC="2012-09-27",
                                                         RFENDTC="2012-09-27",
                                                         RFXSTDTC="2012-09-27",
                                                         RFXENDTC="2012-09-27",
                                                         RFICDTC="2012-09-27",
                                                         RFPENDTC="2012-09-27",
                                                         DTHDTC="2012-09-27",
                                                         DTHFL="N",
                                                         SITEID="TEST",
                                                         INVID="TEST",
                                                         INVNAM="TEST",
                                                         BRTHDTC="2012-09-27",
                                                         AGE=1,
                                                         AGEU="DAYS",
                                                         SEX="U",
                                                         RACE="NOT REPORTED",
                                                         ETHNIC="UNKNOWN",
                                                         ARMCD="TEST",
                                                         ARM="TEST",
                                                         ACTARMCD="TEST",
                                                         ACTARM="TEST",
                                                         ARMNRS="TEST",
                                                         ACTARMUD="TEST",
                                                         COUNTRY="AFG",
                                                         DMDTC="2012-09-27",
                                                         DMDY=1,stringsAsFactors = F),"SDTMIG3.3","DM"),
                 "The following columns of class 'numeric' or 'logical' should be and have been converted to character: STUDYID"),
    data.frame(STUDYID="1",
               DOMAIN="TEST",
               USUBJID="TEST",
               SUBJID="TEST",
               RFSTDTC="2012-09-27",
               RFENDTC="2012-09-27",
               RFXSTDTC="2012-09-27",
               RFXENDTC="2012-09-27",
               RFICDTC="2012-09-27",
               RFPENDTC="2012-09-27",
               DTHDTC="2012-09-27",
               DTHFL="N",
               SITEID="TEST",
               INVID="TEST",
               INVNAM="TEST",
               BRTHDTC="2012-09-27",
               AGE=1,
               AGEU="DAYS",
               SEX="U",
               RACE="NOT REPORTED",
               ETHNIC="UNKNOWN",
               ARMCD="TEST",
               ARM="TEST",
               ACTARMCD="TEST",
               ACTARM="TEST",
               ARMNRS="TEST",
               ACTARMUD="TEST",
               COUNTRY="AFG",
               DMDTC="2012-09-27",
               DMDY=1,stringsAsFactors = F),
    info="The column STUDYID is numeric but should be character, check for warning message and conversion to character")
  expect_equal(
    expect_warning(validate_column_names(data=data.frame(STUDYID="1",
                                                         DOMAIN="TEST",
                                                         USUBJID="TEST",
                                                         SUBJID="TEST",
                                                         RFSTDTC="2012-09-27",
                                                         RFENDTC="2012-09-27",
                                                         RFXSTDTC="2012-09-27",
                                                         RFXENDTC="2012-09-27",
                                                         RFICDTC="2012-09-27",
                                                         RFPENDTC="2012-09-27",
                                                         DTHDTC="2012-09-27",
                                                         DTHFL="N",
                                                         SITEID="TEST",
                                                         INVID="TEST",
                                                         INVNAM="TEST",
                                                         BRTHDTC="2012-09-27",
                                                         AGE="1",
                                                         AGEU="DAYS",
                                                         SEX="U",
                                                         RACE="NOT REPORTED",
                                                         ETHNIC="UNKNOWN",
                                                         ARMCD="TEST",
                                                         ARM="TEST",
                                                         ACTARMCD="TEST",
                                                         ACTARM="TEST",
                                                         ARMNRS="TEST",
                                                         ACTARMUD="TEST",
                                                         COUNTRY="AFG",
                                                         DMDTC="2012-09-27",
                                                         DMDY=1,stringsAsFactors = F),"SDTMIG3.3","DM"),
                   "The following columns of class 'character' should be and have been converted to numeric: AGE"),
    data.frame(STUDYID="1",
               DOMAIN="TEST",
               USUBJID="TEST",
               SUBJID="TEST",
               RFSTDTC="2012-09-27",
               RFENDTC="2012-09-27",
               RFXSTDTC="2012-09-27",
               RFXENDTC="2012-09-27",
               RFICDTC="2012-09-27",
               RFPENDTC="2012-09-27",
               DTHDTC="2012-09-27",
               DTHFL="N",
               SITEID="TEST",
               INVID="TEST",
               INVNAM="TEST",
               BRTHDTC="2012-09-27",
               AGE=1,
               AGEU="DAYS",
               SEX="U",
               RACE="NOT REPORTED",
               ETHNIC="UNKNOWN",
               ARMCD="TEST",
               ARM="TEST",
               ACTARMCD="TEST",
               ACTARM="TEST",
               ARMNRS="TEST",
               ACTARMUD="TEST",
               COUNTRY="AFG",
               DMDTC="2012-09-27",
               DMDY=1,stringsAsFactors = F),
    info="The column AGE is character but should be numeric, check for warning message and conversion to numeric")
  # expect_error(validate_column_names(data=data.frame(STUDYID="1",
  #                                                    DOMAIN="TEST",
  #                                                    USUBJID="TEST",
  #                                                    SUBJID="TEST",
  #                                                    RFSTDTC="2012-09-27",
  #                                                    RFENDTC="2012-09-27",
  #                                                    RFXSTDTC="2012-09-27",
  #                                                    RFXENDTC="2012-09-27",
  #                                                    RFICDTC="2012-09-27",
  #                                                    RFPENDTC="2012-09-27",
  #                                                    DTHDTC="2012-09-27",
  #                                                    DTHFL="N",
  #                                                    SITEID="TEST",
  #                                                    INVID="TEST",
  #                                                    INVNAM="TEST",
  #                                                    BRTHDTC="2012-09-27",
  #                                                    AGE=NA,
  #                                                    AGEU="DAYS",
  #                                                    SEX="U",
  #                                                    RACE="NOT REPORTED",
  #                                                    ETHNIC="UNKNOWN",
  #                                                    ARMCD="TEST",
  #                                                    ARM="TEST",
  #                                                    ACTARMCD="TEST",
  #                                                    ACTARM="TEST",
  #                                                    ARMNRS="TEST",
  #                                                    ACTARMUD="TEST",
  #                                                    COUNTRY="AFG",
  #                                                    DMDTC="2012-09-27",
  #                                                    DMDY=1,stringsAsFactors = F),"SDTMIG3.3","DM"),
  #                  "The following columns in dataset have NA: AGE",
  #   info="The column AGE contains NA, check for error message")
})

test_that("check if columns have controlled terminology", {
  expect_error(validate_column_names(data=data.frame(STUDYID="TEST",
                                                         DOMAIN="TEST",
                                                         USUBJID="TEST",
                                                         SUBJID="TEST",
                                                         RFSTDTC="2012-09-27",
                                                         RFENDTC="2012-09-27",
                                                         RFXSTDTC="2012-09-27",
                                                         RFXENDTC="2012-09-27",
                                                         RFICDTC="2012-09-27",
                                                         RFPENDTC="2012-09-27",
                                                         DTHDTC="2012-09-27",
                                                         DTHFL="Y",
                                                         SITEID="TEST",
                                                         INVID="TEST",
                                                         INVNAM="TEST",
                                                         BRTHDTC="2012-09-27",
                                                         AGE=1,
                                                         AGEU="DAYS",
                                                         SEX="TEST",
                                                         RACE="NOT REPORTED",
                                                         ETHNIC="UNKNOWN",
                                                         ARMCD="TEST",
                                                         ARM="TEST",
                                                         ACTARMCD="TEST",
                                                         ACTARM="TEST",
                                                         ARMNRS="TEST",
                                                         ACTARMUD="TEST",
                                                         COUNTRY="AFG",
                                                         DMDTC="2012-09-27",
                                                         DMDY=1),"SDTMIG3.3","DM"),
                 "The following columns has entries not consistent with controlled terminology: SEX",
                 info="Column SEX has entries not consistent with controlled terminology, check error message")
  expect_silent(validate_column_names(data=data.frame(STUDYID="TEST",
                                                          DOMAIN="TEST",
                                                          USUBJID="TEST",
                                                          SUBJID="TEST",
                                                          RFSTDTC="2012-09-27",
                                                          RFENDTC="2012-09-27",
                                                          RFXSTDTC="2012-09-27",
                                                          RFXENDTC="2012-09-27",
                                                          RFICDTC="2012-09-27",
                                                          RFPENDTC="2012-09-27",
                                                          DTHDTC="2012-09-27",
                                                          DTHFL="Y",
                                                          SITEID="TEST",
                                                          INVID="TEST",
                                                          INVNAM="TEST",
                                                          BRTHDTC="2012-09-27",
                                                          AGE=1,
                                                          AGEU="DAYS",
                                                          SEX="U",
                                                          RACE="NOT REPORTED",
                                                          ETHNIC="UNKNOWN",
                                                          ARMCD="TEST",
                                                          ARM="TEST",
                                                          ACTARMCD="TEST",
                                                          ACTARM="TEST",
                                                          ARMNRS="TEST",
                                                          ACTARMUD="TEST",
                                                          COUNTRY="AFG",
                                                          DMDTC="2012-09-27",
                                                          DMDY=1),"SDTMIG3.3","DM"))

})

test_that("check if columns are consistent with ISO format", {
  expect_error(validate_column_names(data=data.frame(STUDYID="TEST",
                                                     DOMAIN="TEST",
                                                     USUBJID="TEST",
                                                     SUBJID="TEST",
                                                     RFSTDTC="2012-09-27",
                                                     RFENDTC="2012-09-27",
                                                     RFXSTDTC="2012-09-27",
                                                     RFXENDTC="2012-09-27",
                                                     RFICDTC="2012-09-27",
                                                     RFPENDTC="2012-09-27",
                                                     DTHDTC="2012-09-27",
                                                     DTHFL="Y",
                                                     SITEID="TEST",
                                                     INVID="TEST",
                                                     INVNAM="TEST",
                                                     BRTHDTC="2012-09-27",
                                                     AGE=1,
                                                     AGEU="DAYS",
                                                     SEX="U",
                                                     RACE="NOT REPORTED",
                                                     ETHNIC="UNKNOWN",
                                                     ARMCD="TEST",
                                                     ARM="TEST",
                                                     ACTARMCD="TEST",
                                                     ACTARM="TEST",
                                                     ARMNRS="TEST",
                                                     ACTARMUD="TEST",
                                                     COUNTRY="AG",
                                                     DMDTC="2012-09-27",
                                                     DMDY=1),"SDTMIG3.3","DM"),
               "The following columns are not consistent with ISO 3166-1 Alpha-3 standards: COUNTRY",
               info="Column COUNTRY has entries not consistent with ISO 3166-1 Alpha-3 standards, check error message")
  expect_error(validate_column_names(data=data.frame(STUDYID="TEST",
                                                     DOMAIN="TEST",
                                                     USUBJID="TEST",
                                                     SUBJID="TEST",
                                                     RFSTDTC="2012-09-27",
                                                     RFENDTC="2012-09-27",
                                                     RFXSTDTC="2012-09-27",
                                                     RFXENDTC="2012-09-27",
                                                     RFICDTC="2012-09-27",
                                                     RFPENDTC="2012-09-27",
                                                     DTHDTC="2012-09-27",
                                                     DTHFL="Y",
                                                     SITEID="TEST",
                                                     INVID="TEST",
                                                     INVNAM="TEST",
                                                     BRTHDTC="2012-9-27",
                                                     AGE=1,
                                                     AGEU="DAYS",
                                                     SEX="U",
                                                     RACE="NOT REPORTED",
                                                     ETHNIC="UNKNOWN",
                                                     ARMCD="TEST",
                                                     ARM="TEST",
                                                     ACTARMCD="TEST",
                                                     ACTARM="TEST",
                                                     ARMNRS="TEST",
                                                     ACTARMUD="TEST",
                                                     COUNTRY="AFG",
                                                     DMDTC="2012-09-27",
                                                     DMDY=1),"SDTMIG3.3","DM"),
               "The following columns are not consisent with ISO 8601: BRTHDTC",
               info="Column BRTHDTC has entries not consistent with ISO 8601, check error message")

})